spring.application.name=demo
jwt.secret=RH0a2Y7kz2kcyDev0e8EMAErzBwKld9dxQVW3vLQlg0=
jwt.lifetime=90000000
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.threads.virtual.enabled=true
spring.servlet.multipart.max-file-size=4096MB
spring.servlet.multipart.max-request-size=4096MB
server.port=1337
server.forward-headers-strategy=framework

